###########################################################
### Qunying Zhang Personal Website Config (Beautiful Jekyll format)
###########################################################

############################
# --- Required options --- #
############################

title: "Qunying Zhang"
author: "Qunying Zhang"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Home: "index"
  Research Interests: "research"
  CV: "/assets/cv.pdf"
  Contact: "contact"

################
# --- Logo --- #
################

#avatar: "/assets/img/avatar-icon.png"
#round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "zhangqunying243@gmail.com"
  github: "Quinn243"
  linkedin: ""  # You can add your LinkedIn username here if you want
  telephone: "+14126188438"

rss-description: "Qunying Zhang - Personal Website for PhD Application"

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  reddit: false

url-pretty: "quinn243.github.io"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

# Block search engine indexing
robots: noindex

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#################################
# --- Web Analytics Section --- #
#################################

gtag: ""  # Leave empty unless you want Google Analytics

####################
# --- Comments --- #
####################

# (disabled for now)

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
