# Site settings
title: "Qunying Zhang"
email: zhangqunying243@gmail.com
description: "Personal Website of Qunying Zhang — PhD Applicant in Machine Learning, NLP, and Quantitative Research"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quinn243.github.io" # the base hostname & protocol for your site

# SEO (prevent search engines from indexing)
robots: noindex

# Author info
author:
  name: "Qunying Zhang"
  email: zhangqunying243@gmail.com
  phone: "+1-412-618-8438"
  location: "Boston, MA"

# Social links (feel free to add if you have these)
twitter_username: ""
github_username: "Quinn243"
linkedin_username: ""
orcid: ""

# Build settings
markdown: kramdown
theme: beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Personal information to show on homepage (optional)
education:
  - school: "Carnegie Mellon University"
    degree: "Master of Computational Finance"
    location: "Pittsburgh, PA"
    graduation: "Dec 2019"
  - school: "Shanghai Jiao Tong University"
    degree: "B.Sc. Physics (Honor Program)"
    location: "Shanghai, China"
    graduation: "Jun 2018"

experience:
  - job: "Senior Investment Analyst (Quant Research)"
    company: "Mackenzie Investments"
    location: "Boston, MA"
    dates: "Mar 2020 – Present"
  - job: "Data Science Intern"
    company: "Arch Capital Group"
    location: "Raleigh, NC"
    dates: "Jun 2019 – Aug 2019"

skills:
  - Python (Numpy, Scipy, Pandas, Scikit-learn, Keras, Tensorflow, HuggingFace)
  - SQL
  - C++
  - R
  - MATLAB
  - Linux (basic administration)
  - AWS EC2

# Footer info
footer-links-active:
  email: true
  github: true
  linkedin: false

# Google Analytics (optional if you want traffic stats)
google_analytics: ""

# Optional: CV link (put your PDF CV in /assets/ folder)
cv_link: "/assets/cv.pdf"
